version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=SmartGainsDatabase
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
  
  mongo:
    image: mongo:4.4.3
    env_file: ./.env
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./volumes/mongo/data/db/:/data/db/
      - ./volumes/mongo/log/:/var/log/mongodb/
    expose:
      - 27017
    command: ["--bind_ip", "0.0.0.0"]